name: Run Tests

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6

      - name: Setup Pixi
        uses: prefix-dev/setup-pixi@v0.9.6
        with:
          environments: tests

      - name: Run Tests Task
        run: pixi run tests
